#define CD  PC3
#define CE  PB4
#define RD  PB3
#define WR  PB2
#define D0  PB0
#define D1  PB1
#define D2  PD2
#define D3  PD3
#define D4  PD4
#define D5  PD5
#define D6  PD6
#define D7  PD7
#define FS1 PC4
#define RST PC5

#define CD_DDR  DDRC
#define CE_DDR  DDRB
#define RD_DDR  DDRB
#define WR_DDR  DDRB
#define D0_DDR  DDRB
#define D1_DDR  DDRB
#define D2_DDR  DDRD
#define D3_DDR  DDRD
#define D4_DDR  DDRD
#define D5_DDR  DDRD
#define D6_DDR  DDRD
#define D7_DDR  DDRD
#define FS1_DDR DDRC
#define RST_DDR DDRC

#define CD_PORT  PORTC
#define CE_PORT  PORTB
#define RD_PORT  PORTB
#define WR_PORT  PORTB
#define D0_PORT  PORTB
#define D1_PORT  PORTB
#define D2_PORT  PORTD
#define D3_PORT  PORTD
#define D4_PORT  PORTD
#define D5_PORT  PORTD
#define D6_PORT  PORTD
#define D7_PORT  PORTD
#define FS1_PORT PORTC
#define RST_PORT PORTC

#define CD_PIN  PINC
#define CE_PIN  PINB
#define RD_PIN  PINB
#define WR_PIN  PINB
#define D0_PIN  PINB
#define D1_PIN  PINB
#define D2_PIN  PIND
#define D3_PIN  PIND
#define D4_PIN  PIND
#define D5_PIN  PIND
#define D6_PIN  PIND
#define D7_PIN  PIND
#define FS1_PIN PINC
#define RST_PIN PINC